language: cpp
sudo: required
dist: trusty

before_script:
  - sudo sysctl -w net.ipv4.ip_forward=1

script:
  - ./autogen.sh
  - ./configure
  - make -j && make check && sudo make install && make installcheck

notifications:
  slack: keithw:G26dyiLS2bcQcIRrD5eHQ5qG
